### PR TITLE
Visualize course progress

### LINKED ISSUE #367: Visualize exercise completion percentage in the progress page
Maybe only for courses whose completion depend on the completion percentage.

### PR DESCRIPTION
**Pull request by mipyykko**
Looks like this, don't know if this is what we were after:

image

Also added some extra types for backend types to remove VSC warnings.

### CODE REVIEW

**Comment by nygrenh** [comment]
Is this exercise completion percentage or just total points percentage?

Points percentage is also nice to have in the visualization but what I wanted was the number of completed exercises / number of exercises in the course. This percentage should be calculated from tables `exercise_completion` and `exercise`.

But this is also useful for some courses so maybe we should show both things?

**Comment by mipyykko** [comment]
> Is this exercise completion percentage or just total points percentage?

Exercise completion calculated from progresses.

> Points percentage is also nice to have in the visualization but what I wanted was the number of completed exercises / number of exercises in the course. This percentage should be calculated from tables `exercise_completion` and `exercise`.

Okay, let's look into that next.

> But this is also useful for some courses so maybe we should show both things?

Yup.

**Comment by mipyykko** [comment]
Now it has this:

image

Calculated by dividing the exercise completions for the current course by the number of exercises of the current course. Querying has a lot of redundancy, though - we get _all_ the exercise completions from all courses.

**Comment by mipyykko** [comment]
Moved the calculation to backend, now it's `user_course_progresses { exercise_progress { total, exercises } }`. Under `progress` it would involve a few queries less since it would receive the course and user from its parent.

**Review by nygrenh — APPROVED** [review]

**Pull request merged**
