### PR TITLE
API support for UserCourseProgress and UserCourseServiceProgress

### PR DESCRIPTION
**Pull request by Ukonhattu**

### CODE REVIEW

**Comment by Ukonhattu** [comment]
Included also renaming OpenUniversityCourse to CourseAlias and allowing queqying completions registeredCompletions

**Comment by Ukonhattu** [comment]
Forgot permission checks, closing pull rrquest

**Comment by Ukonhattu** [comment]
Added permission checks, reopened

**Comment by Ukonhattu** [comment]
Added query for sinle UserCourseServiceProgress, query for single service, query for single course and some refactoring

**Review by nygrenh — APPROVED** [review]

**Pull request merged**
