### PR TITLE
Research consent

### LINKED ISSUE #412: Global research consent checkbox for new accounts

### PR DESCRIPTION
**Pull request by mipyykko**
- has the research consent in the sign up form
- problem: `getUser` in `backend/middlewares/FetchUser` tries to create new user and this produces a GraphQL error. I think this problem isn't limited just to this case.
- still needs some way to answer the consent question if you're already signed up

### CODE REVIEW

**Comment by mipyykko** [comment]
- changed some logic in `getUser` to prevent the error; still probably needs to eliminate the update altogether if there's nothing to update - probably speeds things up a bit as well
- need to decide on how and where existing users give consent

**Comment by mipyykko** [comment]
- existing users can answer to the research consent
- profile page now has a bugging message if there is no answer at all: 
image
- new settings tab now only has the consent, and selecting the answer mutates directly
- also some translations added -- the points list, completions still have some missing so they're now kinda mixed

An idea would be to have a badge on the profile link if there's something of note, ie. the research consent answer missing.

**Comment by mipyykko** [comment]
- research consent now asked after signing up
- obviously the better way would have been to have it as a sort of stepper, but the create account form component is in a bit of a mess, so the account is actually created before asking the consent now; works, though.

**Comment by mipyykko** [comment]
- the consent is now its own page - now the consent is actually available in the settings and the page after signing up, but user shouldn't generally end up in the latter one, and if one does, no harm done
- the redirect proved to be overzealous, and had a fun time debugging that; hope I didn't break any other redirects doing that
- fixed a bug that's been around for ages: users were always directed to Finnish front page, no matter the language the form was shown in

**Review by nygrenh — APPROVED** [review]

**Pull request merged**
